import sys
import os
import requests
import datetime

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox


class Ui_View(object):
    def setupUi(self, View):
        View.setObjectName("View")
        View.resize(1008, 762)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(229, 107, 73))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 208, 124))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 149, 46))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 110, 75))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 255, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 107, 73))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 237, 233))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 82, 82))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 201, 191))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 47, 50))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 189, 83, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 107, 73))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 208, 124))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 149, 46))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(234, 110, 75))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 255, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(228, 107, 73))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 237, 233))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 82, 82))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 201, 191))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 47, 50))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 189, 83, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 107, 73))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 208, 124))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(247, 149, 46))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(108, 255, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 147, 147))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 82, 82))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(82, 82, 82))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(254, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 47, 50))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 189, 83, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        View.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        View.setFont(font)
        View.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(View)
        self.centralwidget.setObjectName("centralwidget")
        self.line_separator_1 = QtWidgets.QFrame(self.centralwidget)
        self.line_separator_1.setGeometry(QtCore.QRect(0, 80, 1041, 20))
        self.line_separator_1.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_separator_1.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_separator_1.setObjectName("line_separator_1")
        self.Logo_openW = QtWidgets.QLabel(self.centralwidget)
        self.Logo_openW.setGeometry(QtCore.QRect(20, 10, 471, 201))
        self.Logo_openW.setText("")
        self.Logo_openW.setPixmap(QtGui.QPixmap("res/logo_white_cropped.png"))
        self.Logo_openW.setObjectName("Logo_openW")
        self.line_separator_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_separator_2.setGeometry(QtCore.QRect(10, 210, 1001, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        self.line_separator_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.line_separator_2.setFont(font)
        self.line_separator_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_separator_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_separator_2.setObjectName("line_separator_2")
        self.label_d_country = QtWidgets.QLabel(self.centralwidget)
        self.label_d_country.setGeometry(QtCore.QRect(630, 160, 31, 21))
        self.label_d_country.setPalette(palette)
        font.setPointSize(18)
        self.label_d_country.setFont(font)
        self.label_d_country.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d_country.setObjectName("label_d_country")
        self.label_lon = QtWidgets.QLabel(self.centralwidget)
        self.label_lon.setGeometry(QtCore.QRect(690, 150, 31, 21))
        self.label_lon.setPalette(palette)
        font.setPointSize(14)
        self.label_lon.setFont(font)
        self.label_lon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_lon.setObjectName("label_lon")
        self.label_d_lon = QtWidgets.QLabel(self.centralwidget)
        self.label_d_lon.setGeometry(QtCore.QRect(740, 150, 71, 16))
        self.label_d_lon.setPalette(palette)
        font = QtGui.QFont()
        self.label_d_lon.setFont(font)
        self.label_d_lon.setObjectName("label_d_lon")
        self.label_lat = QtWidgets.QLabel(self.centralwidget)
        self.label_lat.setGeometry(QtCore.QRect(690, 180, 31, 21))
        self.label_lat.setPalette(palette)
        self.label_lat.setFont(font)
        self.label_lat.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_lat.setObjectName("label_lat")
        self.label_d_lat = QtWidgets.QLabel(self.centralwidget)
        self.label_d_lat.setGeometry(QtCore.QRect(740, 180, 71, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        self.label_d_lat.setPalette(palette)
        self.label_d_lat.setFont(font)
        self.label_d_lat.setObjectName("label_d_lat")
        self.label_Today = QtWidgets.QLabel(self.centralwidget)
        self.label_Today.setGeometry(QtCore.QRect(20, 240, 91, 31))
        self.label_Today.setPalette(palette)
        font.setPointSize(24)
        self.label_Today.setFont(font)
        self.label_Today.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Today.setObjectName("label_Today")
        self.line_separator_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_separator_3.setGeometry(QtCore.QRect(10, 340, 991, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        self.line_separator_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.line_separator_3.setFont(font)
        self.line_separator_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_separator_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_separator_3.setObjectName("line_separator_3")
        self.line_separator_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_separator_4.setGeometry(QtCore.QRect(0, 570, 1001, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        self.line_separator_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Gill Sans")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.line_separator_4.setFont(font)
        self.line_separator_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_separator_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_separator_4.setObjectName("line_separator_4")
        self.label_Forecast = QtWidgets.QLabel(self.centralwidget)
        self.label_Forecast.setGeometry(QtCore.QRect(20, 360, 111, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        self.label_Forecast.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_Forecast.setFont(font)
        self.label_Forecast.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Forecast.setObjectName("label_Forecast")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(590, 380, 103, 162))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_Forecast_day_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_Forecast_day_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Forecast_day_2.setObjectName("verticalLayout_Forecast_day_2")
        self.label_d_Fore_day_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_d_Fore_day_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_d_Fore_day_2.setFont(font)
        self.label_d_Fore_day_2.setText("")
        self.label_d_Fore_day_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d_Fore_day_2.setObjectName("label_d_Fore_day_2")
        self.verticalLayout_Forecast_day_2.addWidget(self.label_d_Fore_day_2)
        self.label_f_day_2_icon = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_f_day_2_icon.setFont(font)
        self.label_f_day_2_icon.setText("")
        self.label_f_day_2_icon.setPixmap(QtGui.QPixmap(""))
        self.label_f_day_2_icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_f_day_2_icon.setObjectName("label_f_day_2_icon")
        self.verticalLayout_Forecast_day_2.addWidget(self.label_f_day_2_icon)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_fore_Tm_day_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_fore_Tm_day_2.setPalette(palette)
        self.label_fore_Tm_day_2.setFont(font)
        self.label_fore_Tm_day_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_fore_Tm_day_2.setObjectName("label_fore_Tm_day_2")
        self.horizontalLayout_6.addWidget(self.label_fore_Tm_day_2)
        self.label_d_fore_Tm_day_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_d_fore_Tm_day_2.setPalette(palette)
        self.label_d_fore_Tm_day_2.setFont(font)
        self.label_d_fore_Tm_day_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_d_fore_Tm_day_2.setObjectName("label_d_fore_Tm_day_2")
        self.horizontalLayout_6.addWidget(self.label_d_fore_Tm_day_2)
        self.label_Degrees_Tmax_Fore_day_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_Degrees_Tmax_Fore_day_2.setPalette(palette)
        self.label_Degrees_Tmax_Fore_day_2.setFont(font)
        self.label_Degrees_Tmax_Fore_day_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Degrees_Tmax_Fore_day_2.setObjectName("label_Degrees_Tmax_Fore_day_2")
        self.horizontalLayout_6.addWidget(self.label_Degrees_Tmax_Fore_day_2)
        self.verticalLayout_Forecast_day_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_fore_Tmin_day_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_fore_Tmin_day_2.setPalette(palette)
        self.label_fore_Tmin_day_2.setFont(font)
        self.label_fore_Tmin_day_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_fore_Tmin_day_2.setObjectName("label_fore_Tmin_day_2")
        self.horizontalLayout_7.addWidget(self.label_fore_Tmin_day_2)
        self.label_d_fore_Tmin_day_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_d_fore_Tmin_day_2.setPalette(palette)
        self.label_d_fore_Tmin_day_2.setFont(font)
        self.label_d_fore_Tmin_day_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d_fore_Tmin_day_2.setObjectName("label_d_fore_Tmin_day_2")
        self.horizontalLayout_7.addWidget(self.label_d_fore_Tmin_day_2)
        self.label_Degrees_Tmin_Fore_day_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_Degrees_Tmin_Fore_day_2.setPalette(palette)
        self.label_Degrees_Tmin_Fore_day_2.setFont(font)
        self.label_Degrees_Tmin_Fore_day_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Degrees_Tmin_Fore_day_2.setObjectName("label_Degrees_Tmin_Fore_day_2")
        self.horizontalLayout_7.addWidget(self.label_Degrees_Tmin_Fore_day_2)
        self.verticalLayout_Forecast_day_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_UVI_Fore_day_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_UVI_Fore_day_2.setPalette(palette)
        self.label_UVI_Fore_day_2.setFont(font)
        self.label_UVI_Fore_day_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_UVI_Fore_day_2.setObjectName("label_UVI_Fore_day_2")
        self.horizontalLayout_8.addWidget(self.label_UVI_Fore_day_2)
        self.label_d_fore_UVI_day_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_d_fore_UVI_day_2.setPalette(palette)
        self.label_d_fore_UVI_day_2.setFont(font)
        self.label_d_fore_UVI_day_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d_fore_UVI_day_2.setObjectName("label_d_fore_UVI_day_2")
        self.horizontalLayout_8.addWidget(self.label_d_fore_UVI_day_2)
        self.verticalLayout_Forecast_day_2.addLayout(self.horizontalLayout_8)
        self.line_separator_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_separator_5.setGeometry(QtCore.QRect(0, 650, 1001, 21))
        self.line_separator_5.setPalette(palette)
        self.line_separator_5.setFont(font)
        self.line_separator_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_separator_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_separator_5.setObjectName("line_separator_5")
        self.label_Alerts = QtWidgets.QLabel(self.centralwidget)
        self.label_Alerts.setGeometry(QtCore.QRect(10, 590, 111, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        self.label_Alerts.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_Alerts.setFont(font)
        self.label_Alerts.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Alerts.setObjectName("label_Alerts")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(530, 100, 431, 38))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_enter_City = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_enter_City.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_enter_City.setObjectName("horizontalLayout_enter_City")
        self.label_City = QtWidgets.QLabel(self.layoutWidget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        self.label_City.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_City.setFont(font)
        self.label_City.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.label_City.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_City.setObjectName("label_City")
        self.horizontalLayout_enter_City.addWidget(self.label_City)
        self.lineEdit_City = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_City.setFont(font)
        self.lineEdit_City.setObjectName("lineEdit_City")
        self.horizontalLayout_enter_City.addWidget(self.lineEdit_City)
        self.pushButton_Go = QtWidgets.QPushButton(self.layoutWidget1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 248, 23))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 109, 74))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 37, 33))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 248, 23))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 109, 74))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 37, 33))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 248, 23))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 147, 147))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Highlight, brush)
        self.pushButton_Go.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Go.setFont(font)
        self.pushButton_Go.setObjectName("pushButton_Go")
        self.horizontalLayout_enter_City.addWidget(self.pushButton_Go)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(150, 230, 311, 52))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_Current_temp = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_Current_temp.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_Current_temp.setObjectName("horizontalLayout_Current_temp")
        self.label_d_today_icon = QtWidgets.QLabel(self.layoutWidget2)
        self.label_d_today_icon.setText("")
        self.label_d_today_icon.setPixmap(QtGui.QPixmap(""))
        self.label_d_today_icon.setObjectName("label_d_today_icon")
        self.horizontalLayout_Current_temp.addWidget(self.label_d_today_icon)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Current_temp.addItem(spacerItem)
        self.label_d_T_today = QtWidgets.QLabel(self.layoutWidget2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        self.label_d_T_today.setPalette(palette)
        font.setPointSize(18)
        self.label_d_T_today.setFont(font)
        self.label_d_T_today.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d_T_today.setObjectName("label_d_T_today")
        self.horizontalLayout_Current_temp.addWidget(self.label_d_T_today)
        self.label_Degrees_Today = QtWidgets.QLabel(self.layoutWidget2)
        self.label_Degrees_Today.setPalette(palette)
        font.setPointSize(18)
        self.label_Degrees_Today.setFont(font)
        self.label_Degrees_Today.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Degrees_Today.setObjectName("label_Degrees_Today")
        self.horizontalLayout_Current_temp.addWidget(self.label_Degrees_Today)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Current_temp.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Current_temp.addItem(spacerItem2)
        self.label_feels_like = QtWidgets.QLabel(self.layoutWidget2)
        self.label_feels_like.setPalette(palette)
        font.setPointSize(18)
        self.label_feels_like.setFont(font)
        self.label_feels_like.setObjectName("label_feels_like")
        self.horizontalLayout_Current_temp.addWidget(self.label_feels_like)
        self.label_d_feels_today = QtWidgets.QLabel(self.layoutWidget2)
        self.label_d_feels_today.setPalette(palette)
        font.setPointSize(18)
        self.label_d_feels_today.setFont(font)
        self.label_d_feels_today.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d_feels_today.setObjectName("label_d_feels_today")
        self.horizontalLayout_Current_temp.addWidget(self.label_d_feels_today)
        self.label_Degrees_Today_f = QtWidgets.QLabel(self.layoutWidget2)
        self.label_Degrees_Today_f.setPalette(palette)
        font.setPointSize(18)
        font.setBold(True)
        self.label_Degrees_Today_f.setFont(font)
        self.label_Degrees_Today_f.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Degrees_Today_f.setObjectName("label_Degrees_Today_f")
        self.horizontalLayout_Current_temp.addWidget(self.label_Degrees_Today_f)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(360, 380, 103, 162))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_Forecast_day_1 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_Forecast_day_1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Forecast_day_1.setObjectName("verticalLayout_Forecast_day_1")
        self.label_d_Fore_day_1 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_d_Fore_day_1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_d_Fore_day_1.setFont(font)
        self.label_d_Fore_day_1.setText("")
        self.label_d_Fore_day_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d_Fore_day_1.setObjectName("label_d_Fore_day_1")
        self.verticalLayout_Forecast_day_1.addWidget(self.label_d_Fore_day_1)
        self.label_f_day_1_icon = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.label_f_day_1_icon.setFont(font)
        self.label_f_day_1_icon.setText("")
        self.label_f_day_1_icon.setPixmap(QtGui.QPixmap(""))
        self.label_f_day_1_icon.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_f_day_1_icon.setObjectName("label_f_day_1_icon")
        self.verticalLayout_Forecast_day_1.addWidget(self.label_f_day_1_icon)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_fore_Tm_day_1 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_fore_Tm_day_1.setPalette(palette)
        font.setPointSize(14)
        self.label_fore_Tm_day_1.setFont(font)
        self.label_fore_Tm_day_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_fore_Tm_day_1.setObjectName("label_fore_Tm_day_1")
        self.horizontalLayout_5.addWidget(self.label_fore_Tm_day_1)
        self.label_d_fore_Tm_day_1 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_d_fore_Tm_day_1.setPalette(palette)
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_d_fore_Tm_day_1.setFont(font)
        self.label_d_fore_Tm_day_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_d_fore_Tm_day_1.setObjectName("label_d_fore_Tm_day_1")
        self.horizontalLayout_5.addWidget(self.label_d_fore_Tm_day_1)
        self.label_Degrees_Tmax_Fore_day_1 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_Degrees_Tmax_Fore_day_1.setPalette(palette)
        self.label_Degrees_Tmax_Fore_day_1.setFont(font)
        self.label_Degrees_Tmax_Fore_day_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Degrees_Tmax_Fore_day_1.setObjectName("label_Degrees_Tmax_Fore_day_1")
        self.horizontalLayout_5.addWidget(self.label_Degrees_Tmax_Fore_day_1)
        self.verticalLayout_Forecast_day_1.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_fore_Tmin_day_1 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_fore_Tmin_day_1.setPalette(palette)
        self.label_fore_Tmin_day_1.setFont(font)
        self.label_fore_Tmin_day_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_fore_Tmin_day_1.setObjectName("label_fore_Tmin_day_1")
        self.horizontalLayout_4.addWidget(self.label_fore_Tmin_day_1)
        self.label_d_fore_Tmin_day_1 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_d_fore_Tmin_day_1.setPalette(palette)
        self.label_d_fore_Tmin_day_1.setFont(font)
        self.label_d_fore_Tmin_day_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d_fore_Tmin_day_1.setObjectName("label_d_fore_Tmin_day_1")
        self.horizontalLayout_4.addWidget(self.label_d_fore_Tmin_day_1)
        self.label_Degrees_Tmin_Fore_day_1 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_Degrees_Tmin_Fore_day_1.setPalette(palette)
        self.label_Degrees_Tmin_Fore_day_1.setFont(font)
        self.label_Degrees_Tmin_Fore_day_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Degrees_Tmin_Fore_day_1.setObjectName("label_Degrees_Tmin_Fore_day_1")
        self.horizontalLayout_4.addWidget(self.label_Degrees_Tmin_Fore_day_1)
        self.verticalLayout_Forecast_day_1.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_UVI_Fore_day_1 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_UVI_Fore_day_1.setPalette(palette)
        self.label_UVI_Fore_day_1.setFont(font)
        self.label_UVI_Fore_day_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_UVI_Fore_day_1.setObjectName("label_UVI_Fore_day_1")
        self.horizontalLayout_3.addWidget(self.label_UVI_Fore_day_1)
        self.label_d_fore_UVI_day_1 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_d_fore_UVI_day_1.setPalette(palette)
        self.label_d_fore_UVI_day_1.setFont(font)
        self.label_d_fore_UVI_day_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d_fore_UVI_day_1.setObjectName("label_d_fore_UVI_day_1")
        self.horizontalLayout_3.addWidget(self.label_d_fore_UVI_day_1)
        self.verticalLayout_Forecast_day_1.addLayout(self.horizontalLayout_3)
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(220, 300, 461, 31))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_Current_H_UVI_Wind = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_Current_H_UVI_Wind.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_Current_H_UVI_Wind.setObjectName("horizontalLayout_Current_H_UVI_Wind")
        self.label_Humidity_today = QtWidgets.QLabel(self.layoutWidget4)
        self.label_Humidity_today.setPalette(palette)
        self.label_Humidity_today.setFont(font)
        self.label_Humidity_today.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Humidity_today.setObjectName("label_Humidity_today")
        self.horizontalLayout_Current_H_UVI_Wind.addWidget(self.label_Humidity_today)
        self.label_d_humidity_today = QtWidgets.QLabel(self.layoutWidget4)
        self.label_d_humidity_today.setPalette(palette)
        self.label_d_humidity_today.setFont(font)
        self.label_d_humidity_today.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d_humidity_today.setObjectName("label_d_humidity_today")
        self.horizontalLayout_Current_H_UVI_Wind.addWidget(self.label_d_humidity_today)
        self.label_percert_humidity = QtWidgets.QLabel(self.layoutWidget4)
        self.label_percert_humidity.setPalette(palette)
        self.label_percert_humidity.setFont(font)
        self.label_percert_humidity.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_percert_humidity.setObjectName("label_percert_humidity")
        self.horizontalLayout_Current_H_UVI_Wind.addWidget(self.label_percert_humidity)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Current_H_UVI_Wind.addItem(spacerItem3)
        self.label_UVI_today = QtWidgets.QLabel(self.layoutWidget4)
        self.label_UVI_today.setPalette(palette)
        self.label_UVI_today.setFont(font)
        self.label_UVI_today.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_UVI_today.setObjectName("label_UVI_today")
        self.horizontalLayout_Current_H_UVI_Wind.addWidget(self.label_UVI_today)
        self.label_d_uvi_today = QtWidgets.QLabel(self.layoutWidget4)
        self.label_d_uvi_today.setPalette(palette)
        self.label_d_uvi_today.setFont(font)
        self.label_d_uvi_today.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d_uvi_today.setObjectName("label_d_uvi_today")
        self.horizontalLayout_Current_H_UVI_Wind.addWidget(self.label_d_uvi_today)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Current_H_UVI_Wind.addItem(spacerItem4)
        self.label_Wspeed_today = QtWidgets.QLabel(self.layoutWidget4)
        self.label_Wspeed_today.setPalette(palette)
        self.label_Wspeed_today.setFont(font)
        self.label_Wspeed_today.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Wspeed_today.setObjectName("label_Wspeed_today")
        self.horizontalLayout_Current_H_UVI_Wind.addWidget(self.label_Wspeed_today)
        self.label_d_WSpeed_today = QtWidgets.QLabel(self.layoutWidget4)
        self.label_d_WSpeed_today.setPalette(palette)
        self.label_d_WSpeed_today.setFont(font)
        self.label_d_WSpeed_today.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d_WSpeed_today.setObjectName("label_d_WSpeed_today")
        self.horizontalLayout_Current_H_UVI_Wind.addWidget(self.label_d_WSpeed_today)
        self.label_Km_WSpeed_today = QtWidgets.QLabel(self.layoutWidget4)
        self.label_Km_WSpeed_today.setPalette(palette)
        self.label_Km_WSpeed_today.setFont(font)
        self.label_Km_WSpeed_today.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Km_WSpeed_today.setObjectName("label_Km_WSpeed_today")
        self.horizontalLayout_Current_H_UVI_Wind.addWidget(self.label_Km_WSpeed_today)
        self.layoutWidget5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(590, 240, 301, 31))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_Current_Sunrise_Sunset = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_Current_Sunrise_Sunset.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_Current_Sunrise_Sunset.setObjectName("horizontalLayout_Current_Sunrise_Sunset")
        self.label_Sunrise_today = QtWidgets.QLabel(self.layoutWidget5)
        self.label_Sunrise_today.setPalette(palette)
        font.setPointSize(14)
        self.label_Sunrise_today.setFont(font)
        self.label_Sunrise_today.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Sunrise_today.setObjectName("label_Sunrise_today")
        self.horizontalLayout_Current_Sunrise_Sunset.addWidget(self.label_Sunrise_today)
        self.label_d_Sunrise_today = QtWidgets.QLabel(self.layoutWidget5)
        self.label_d_Sunrise_today.setPalette(palette)
        font.setPointSize(14)
        self.label_d_Sunrise_today.setFont(font)
        self.label_d_Sunrise_today.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d_Sunrise_today.setObjectName("label_d_Sunrise_today")
        self.horizontalLayout_Current_Sunrise_Sunset.addWidget(self.label_d_Sunrise_today)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Current_Sunrise_Sunset.addItem(spacerItem5)
        self.label_Sunset_today = QtWidgets.QLabel(self.layoutWidget5)
        self.label_Sunset_today.setPalette(palette)
        font.setPointSize(14)
        self.label_Sunset_today.setFont(font)
        self.label_Sunset_today.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Sunset_today.setObjectName("label_Sunset_today")
        self.horizontalLayout_Current_Sunrise_Sunset.addWidget(self.label_Sunset_today)

        self.label_d_Sunset_today = QtWidgets.QLabel(self.layoutWidget5)
        self.label_d_Sunset_today.setPalette(palette)
        font.setPointSize(14)
        self.label_d_Sunset_today.setFont(font)
        self.label_d_Sunset_today.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d_Sunset_today.setObjectName("label_d_Sunset_today")
        self.horizontalLayout_Current_Sunrise_Sunset.addWidget(self.label_d_Sunset_today)
        self.layoutWidget6 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(140, 600, 837, 51))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_Alerts = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_Alerts.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_Alerts.setObjectName("verticalLayout_Alerts")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")

        self.label_d_alerts_sender = QtWidgets.QLabel(self.layoutWidget6)
        self.label_d_alerts_sender.setPalette(palette)
        font.setPointSize(14)
        self.label_d_alerts_sender.setFont(font)
        self.label_d_alerts_sender.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d_alerts_sender.setObjectName("label_d_alerts_sender")
        self.horizontalLayout_26.addWidget(self.label_d_alerts_sender)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem6)
        
        self.label_d_alerts_start = QtWidgets.QLabel(self.layoutWidget6)
        self.label_d_alerts_start.setPalette(palette)
        font.setPointSize(14)
        self.label_d_alerts_start.setFont(font)
        self.label_d_alerts_start.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d_alerts_start.setObjectName("label_d_alerts_start")
        self.horizontalLayout_26.addWidget(self.label_d_alerts_start)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem7)
        
        self.label_d_alerts_ends = QtWidgets.QLabel(self.layoutWidget6)
        self.label_d_alerts_ends.setPalette(palette)
        font.setPointSize(14)
        self.label_d_alerts_ends.setFont(font)
        self.label_d_alerts_ends.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d_alerts_ends.setObjectName("label_d_alerts_ends")
        self.horizontalLayout_26.addWidget(self.label_d_alerts_ends)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem8)
        self.label_d_alerts_event = QtWidgets.QLabel(self.layoutWidget6)
        self.label_d_alerts_event.setPalette(palette)
        
        font.setPointSize(14)
        self.label_d_alerts_event.setFont(font)
        self.label_d_alerts_event.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d_alerts_event.setObjectName("label_d_alerts_event")
        self.horizontalLayout_26.addWidget(self.label_d_alerts_event)
        self.verticalLayout_Alerts.addLayout(self.horizontalLayout_26)
        self.label_d_alerts_description = QtWidgets.QLabel(self.layoutWidget6)
        
        self.label_d_alerts_description.setPalette(palette)
        font.setPointSize(14)
        self.label_d_alerts_description.setFont(font)
        self.label_d_alerts_description.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d_alerts_description.setObjectName("label_d_alerts_description")
        self.verticalLayout_Alerts.addWidget(self.label_d_alerts_description)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(770, 670, 194, 36))
        self.widget.setObjectName("widget")
        self.horizontalLayout_buttons_quit_clear = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_buttons_quit_clear.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_buttons_quit_clear.setObjectName("horizontalLayout_buttons_quit_clear")
        self.pushButton_Clear = QtWidgets.QPushButton(self.widget)
        font.setPointSize(16)
        self.pushButton_Clear.setFont(font)
        self.pushButton_Clear.setObjectName("pushButton_Clear")
        self.horizontalLayout_buttons_quit_clear.addWidget(self.pushButton_Clear)
        self.pushButton_Quit = QtWidgets.QPushButton(self.widget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 248, 23))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 109, 74))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 37, 33))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 248, 23))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(232, 109, 74))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(244, 37, 33))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 63))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(231, 248, 23))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(147, 147, 147))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Highlight, brush)
        self.pushButton_Quit.setPalette(palette)
        font.setPointSize(16)
        self.pushButton_Quit.setFont(font)
        self.pushButton_Quit.setObjectName("pushButton_Quit")
        self.horizontalLayout_buttons_quit_clear.addWidget(self.pushButton_Quit)
        View.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(View)
        self.statusbar.setObjectName("statusbar")
        View.setStatusBar(self.statusbar)

        self.retranslateUi(View)
        self.pushButton_Quit.clicked.connect(View.close)
        self.pushButton_Go.clicked.connect(self._button_go_weather)
        self.pushButton_Clear.clicked.connect(self._button_clean_labels)
        QtCore.QMetaObject.connectSlotsByName(View)

    def retranslateUi(self, View):
        _translate = QtCore.QCoreApplication.translate
        View.setWindowTitle(_translate("View", "Open Weather App"))
        self.label_d_country.setText(_translate("View", ""))
        self.label_lon.setText(_translate("View", "lon"))
        self.label_d_lon.setText(_translate("View", ""))
        self.label_lat.setText(_translate("View", "lat"))
        self.label_d_lat.setText(_translate("View", ""))
        self.label_Today.setStatusTip(_translate("View", "TODAY: Current weather"))
        self.label_Today.setText(_translate("View", "Today"))
        self.label_Forecast.setStatusTip(_translate("View", "FORECAST: You can see forescat weather for the rest of the week."))
        self.label_Forecast.setText(_translate("View", "Forecast"))
        self.label_fore_Tm_day_2.setText(_translate("View", "Tmax"))
        self.label_d_fore_Tm_day_2.setText(_translate("View", ""))
        self.label_Degrees_Tmax_Fore_day_2.setText(_translate("View", "ºC"))
        self.label_fore_Tmin_day_2.setText(_translate("View", "Tmin"))
        self.label_d_fore_Tmin_day_2.setText(_translate("View", ""))
        self.label_Degrees_Tmin_Fore_day_2.setText(_translate("View", "ºC"))
        self.label_UVI_Fore_day_2.setText(_translate("View", "UVI"))
        self.label_d_fore_UVI_day_2.setText(_translate("View", ""))
        self.label_Alerts.setStatusTip(_translate("View", "ALERTS: If there is a special alert you will see in this area"))
        self.label_Alerts.setText(_translate("View", "Alerts"))
        self.label_City.setText(_translate("View", "City ==>"))
        self.lineEdit_City.setStatusTip(_translate("View", "Enter the name of a city"))
        self.lineEdit_City.setText(_translate("View", ""))
        self.pushButton_Go.setStatusTip(_translate("View", "GO WEATHER: Push for getting info weather en forecast. Shortcut: INTRO"))
        self.pushButton_Go.setText(_translate("View", "Go Weather"))
        self.pushButton_Go.setShortcut(_translate("View", "Return"))
        self.label_d_T_today.setStatusTip(_translate("View", "Current temperature"))
        self.label_d_T_today.setText(_translate("View", ""))
        self.label_Degrees_Today.setText(_translate("View", "ºC"))
        self.label_feels_like.setText(_translate("View", "Feels Like"))
        self.label_d_feels_today.setText(_translate("View", ""))
        self.label_Degrees_Today_f.setText(_translate("View", "ºC"))
        self.label_fore_Tm_day_1.setText(_translate("View", "Tmax"))
        self.label_d_fore_Tm_day_1.setText(_translate("View", ""))
        self.label_Degrees_Tmax_Fore_day_1.setText(_translate("View", "ºC"))
        self.label_fore_Tmin_day_1.setText(_translate("View", "Tmin"))
        self.label_d_fore_Tmin_day_1.setText(_translate("View", ""))
        self.label_Degrees_Tmin_Fore_day_1.setText(_translate("View", "ºC"))
        self.label_UVI_Fore_day_1.setText(_translate("View", "UVI"))
        self.label_d_fore_UVI_day_1.setText(_translate("View", ""))
        self.label_Humidity_today.setText(_translate("View", "Humidity"))
        self.label_d_humidity_today.setText(_translate("View", ""))
        self.label_percert_humidity.setText(_translate("View", "%"))
        self.label_UVI_today.setText(_translate("View", "UVI"))
        self.label_d_uvi_today.setText(_translate("View", ""))
        self.label_Wspeed_today.setText(_translate("View", "Wind Speed"))
        self.label_d_WSpeed_today.setText(_translate("View", ""))
        self.label_Km_WSpeed_today.setText(_translate("View", "Km/h"))
        self.label_Sunrise_today.setText(_translate("View", "Sunrise"))
        self.label_d_Sunrise_today.setText(_translate("View", ""))
        self.label_Sunset_today.setText(_translate("View", "Sunset"))
        self.label_d_Sunset_today.setText(_translate("View", ""))
        self.label_d_alerts_sender.setText(_translate("View", ""))
        self.label_d_alerts_start.setText(_translate("View", ""))
        self.label_d_alerts_ends.setText(_translate("View", ""))
        self.label_d_alerts_event.setText(_translate("View", ""))
        self.label_d_alerts_description.setText(_translate("View", ""))
        self.label_d_Fore_day_1.setText(_translate("View",""))
        self.label_d_Fore_day_2.setText(_translate("View",""))
        self.pushButton_Clear.setStatusTip(_translate("View", "CLEAR: Clear data labels.  Shortcut: SHIFT+COMMAND+C"))
        self.pushButton_Clear.setText(_translate("View", "Clear"))
        self.pushButton_Clear.setShortcut(_translate("View", "Ctrl+Shift+C"))
        self.pushButton_Quit.setStatusTip(_translate("View", "Quit Application.  Shortcut: COMMAND+E"))
        self.pushButton_Quit.setText(_translate("View", "Quit"))
        self.pushButton_Quit.setShortcut(_translate("View", "Ctrl+E"))

         
    def _button_go_weather(self):

        city=str(self.lineEdit_City.text())

        if city == "":
            self._show_popup_null_label()
            self._button_clean_labels()
        else:
            self._set_city(city)
            self._get_parameters_current()
            self._scrapper_7_forecast()
            self._get_parameters_forecast()
            self._set_labels()

    def _button_clean_labels(self):
        self._clean_labels()
        self._clean_labels_alerts()
        self._set_labels()

    def _clean_labels(self):
        
        self.lineEdit_City.setText("")
        self.filepath=""
        self.filepathf1=""
        self.filepathf2=""
        self.label_country=""
        self.label_lon=""
        self.label_lat=""
        self.label_T_today=""
        self.label_humidity_today=""
        self.label_uvi_today=""
        self.label_WSpeed_today=""
        self.label_Sunrise_today=""
        self.label_Sunset_today=""
        self.label_Fore_day_1=""
        self.label_Fore_day_2=""
        self.label_fore_Tm_day_1=""
        self.label_fore_Tmin_day_1=""
        self.label_fore_UVI_day_1=""
        self.label_fore_Tm_day_2=""
        self.label_fore_Tmin_day_2=""
        self.label_fore_UVI_day_2=""
        self.label_feels_today=""

    def _clean_labels_alerts(self):

        self.label_alerts_sender=""
        self.label_alerts_start=""
        self.label_alerts_ends=""
        self.label_alerts_event=""
        self.label_alerts_description=""

    def _set_city(self,city):

        self.units="metric"
        self.api_key ="9a16a8e5458b6fdb0d040e46ee221bca"
        self.language="es"
        self._scrapper_current_weather(city)

    def _scrapper_current_weather(self,city):
        # Get current weather and coord of the city.
        
        endpoint=(f"http://api.openweathermap.org/data/2.5/weather?q={city}&units={self.units}&uk&lang={self.language}&APPID={self.api_key}")
        response= requests.get(endpoint)
        self.dict_current=response.json()
        
    def _scrapper_7_forecast(self):
         # Get 7 days forescast weather
        try:
            self.lat=self.dict_current['coord']['lat']
        except KeyError:
            return
        self.lon=self.dict_current['coord']['lon']
        endpoint_7days=(f"https://api.openweathermap.org/data/2.5/onecall?lat={self.lat}&lon={self.lon}&units={self.units}&exclude=hourly,minutely&appid={self.api_key}")
        response_7days= requests.get(endpoint_7days)
        self.dict_7days=response_7days.json()      
        
    def _get_parameters_current(self):

        try:
            icon_weather=self.dict_current['weather'][0]['icon']
        except KeyError:
            self._show_popup_city_notfound()
            self._button_clean_labels()
            return

        file_icon=(f"http://openweathermap.org/img/w/{icon_weather}.png")
        _path=os.path.join("res","weathericon.png")
        f=open(_path,'wb')
        response_icon=requests.get(file_icon)
        f.write(response_icon.content)
        f.close
        self.temp = str(round(self.dict_current['main']['temp']))
        self.temp_feel=str(round(self.dict_current['main']['feels_like']))
        self.filepath=_path
        self.label_country=self.dict_current['sys']['country']
        self.label_lon=str(self.dict_current['coord']['lon'])
        self.label_lat=str(self.dict_current['coord']['lat'])
        self.label_T_today=str(round(self.dict_current['main']['temp']))
        self.label_feels_today=str(round(self.dict_current['main']['feels_like']))
        self.label_humidity_today=str(self.dict_current['main']['humidity'])
        self.label_WSpeed_today=str(round((self.dict_current['wind']['speed'])*3600/1000))
        self.label_Sunrise_today=self._get_data_time(self.dict_current['sys']['sunrise'], "hour")
        self.label_Sunset_today=self._get_data_time(self.dict_current['sys']['sunset'], "hour")
           

    def _get_parameters_forecast(self):
        
        try:
            self.dict_7days
        except AttributeError:
            
            return
        self.label_uvi_today=str(round(self.dict_7days['current']['uvi']))
        icon_weather_fore_1=self.dict_7days['daily'][1]['weather'][0]['icon']
        file_icon1=(f"http://openweathermap.org/img/w/{icon_weather_fore_1}.png")
        _path1=os.path.join("res","weathericon_fore_1.png")
        f=open(_path1,'wb')
        response_icon=requests.get(file_icon1)
        f.write(response_icon.content)
        f.close
        self.filepathf1=_path1
        icon_weather_fore_2=self.dict_7days['daily'][2]['weather'][0]['icon']
        file_icon2=(f"http://openweathermap.org/img/w/{icon_weather_fore_2}.png")
        _path2=os.path.join("res","weathericon_fore_2.png")
        f=open(_path2,'wb')
        response_icon=requests.get(file_icon2)
        f.write(response_icon.content)
        f.close
        self.filepathf2=_path2
        self.label_fore_Tm_day_1 = str(round(self.dict_7days['daily'][1]['temp']['max']))
        self.label_fore_Tmin_day_1 = str(round(self.dict_7days['daily'][1]['temp']['min']))
        self.label_fore_UVI_day_1 = str(int(self.dict_7days['daily'][1]['uvi']))
        self.label_fore_Tm_day_2 = str(round(self.dict_7days['daily'][2]['temp']['max']))
        self.label_fore_Tmin_day_2 = str(round(self.dict_7days['daily'][2]['temp']['min']))
        self.label_fore_UVI_day_2 = str(int(self.dict_7days['daily'][2]['uvi']))
        self.label_Fore_day_1=self._get_data_time(self.dict_7days['daily'][1]['dt'], "day")
        self.label_Fore_day_2=self._get_data_time(self.dict_7days['daily'][2]['dt'], "day")

        # Alerts
        try:
            print(self.dict_7days['alerts'])
        except KeyError:
            print("There are any alerts at the moment")
            self._clean_labels_alerts()
            return

        self.label_alerts_sender=self.dict_7days['alerts'][0]['sender_name']
        self.label_alerts_event=self.dict_7days['alerts'][0]['event']
        self.label_alerts_description=self.dict_7days['alerts'][0]['description']
        self.label_alerts_start=self._get_data_time(self.dict_7days['alerts'][0]['start'], "full_data")
        self.label_alerts_ends=self._get_data_time(self.dict_7days['alerts'][0]['end'], "full_data")

    def _get_icon(self,*parameters):
        pass

    def _get_data_time(self,data,format):
        if format == "full_data":
            timestamp = datetime.datetime.fromtimestamp(data)
            _data_time= str(timestamp.strftime('%d-%m-%Y %H:%M'))
            return _data_time
        elif format == "day":
            timestamp = datetime.datetime.fromtimestamp(data)
            _data_time= str(timestamp.strftime('%d-%m'))
            return _data_time
        elif format == "hour":
            timestamp = datetime.datetime.fromtimestamp(data)
            _data_time= str(timestamp.strftime('%H:%M'))
            return _data_time

    def _set_labels(self):

        _translate = QtCore.QCoreApplication.translate
        self.label_d_today_icon.setPixmap(QtGui.QPixmap(self.filepath))
        self.label_f_day_1_icon.setPixmap(QtGui.QPixmap(self.filepathf1))
        self.label_f_day_2_icon.setPixmap(QtGui.QPixmap(self.filepathf2))
        
        self.label_d_country.setText(_translate("View", self.label_country))
        self.label_d_lon.setText(_translate("View", self.label_lon))
        self.label_d_lat.setText(_translate("View", self.label_lat))
        self.label_d_fore_Tm_day_2.setText(_translate("View", self.label_fore_Tm_day_2))
        self.label_d_fore_Tmin_day_2.setText(_translate("View", self.label_fore_Tmin_day_2))
        self.label_d_fore_UVI_day_2.setText(_translate("View", self.label_fore_UVI_day_2))
        self.label_d_T_today.setText(_translate("View", self.label_T_today))
        self.label_d_feels_today.setText(_translate("View", self.label_feels_today))
        self.label_d_fore_Tm_day_1.setText(_translate("View", self.label_fore_Tm_day_1))
        self.label_d_fore_Tmin_day_1.setText(_translate("View", self.label_fore_Tmin_day_1))
        self.label_d_fore_UVI_day_1.setText(_translate("View", self.label_fore_UVI_day_1))
        self.label_d_humidity_today.setText(_translate("View", self.label_humidity_today))
        self.label_d_uvi_today.setText(_translate("View", self.label_uvi_today))
        self.label_d_WSpeed_today.setText(_translate("View", self.label_WSpeed_today))
        self.label_d_Sunrise_today.setText(_translate("View", self.label_Sunrise_today))
        self.label_d_Sunset_today.setText(_translate("View", self.label_Sunset_today))

        self.label_d_alerts_sender.setText(_translate("View",self.label_alerts_sender))
        self.label_d_alerts_start.setText(_translate("View",self.label_alerts_start))
        self.label_d_alerts_ends.setText(_translate("View",self.label_alerts_ends))
        self.label_d_alerts_event.setText(_translate("View",self.label_alerts_event))
        self.label_d_alerts_description.setText(_translate("View",self.label_alerts_description))
        self.label_d_Fore_day_1.setText(_translate("View",self.label_Fore_day_1))
        self.label_d_Fore_day_2.setText(_translate("View",self.label_Fore_day_2))

        

    def _show_popup_null_label(self):
        dlg = QMessageBox()
        dlg.setWindowTitle("Error") 
        dlg.setText("City can't be null.\nPlease enter a city name")
        dlg.setIcon(QMessageBox.Icon.Warning)
        button = dlg.exec()

    def _show_popup_city_notfound(self):
        dlg = QMessageBox()
        dlg.setWindowTitle("Error") 
        dlg.setText("City not found or doesn't exit.\nTry again")
        dlg.setIcon(QMessageBox.Icon.Warning)
        button = dlg.exec()


def main():

    app = QtWidgets.QApplication(sys.argv)
    View = QtWidgets.QMainWindow()
    ui = Ui_View()
    ui.setupUi(View)
    View.show()
    sys.exit(app.exec())

if __name__ == "__main__":
    main()
