# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_window(object):

    font = QtGui.QFont()
    font.setFamily("Barlow")
    font.setPointSize(10)
    font.setBold(True)
    font.setWeight(75)

    def setupUi(self, window):
        window.setObjectName("window")
        self.horizontalLayoutWidget = QtWidgets.QWidget(window)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(129, 320, 191, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        
        self.pushButton_2.setFont(Ui_window.font)
        self.pushButton_2.setObjectName("Edit")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        
        self.pushButton.setFont(Ui_window.font)
        self.pushButton.setObjectName("Quit")
        self.horizontalLayout.addWidget(self.pushButton)

        self.retranslateUi(window)
        self.pushButton.pressed.connect(window.close)
        self.pushButton_2.pressed.connect(self.update)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "window"))
        
    
    def update(self):
        pass

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QWidget()
    ui = Ui_window()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec())
